# This file was generated by GoReleaser. DO NOT EDIT.
cask "wharf" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "b90d78ba15a665203d6fdbfab370688dd9c340c7bcb8cce5d547061fab3cd4d5"
      url "https://github.com/Janne6565/wharf-tui/releases/download/v#{version}/wharf_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d40d192132a4d339a9274abd2d435f94f118c795ad2acdd406d80ead75f3a95"
      url "https://github.com/Janne6565/wharf-tui/releases/download/v#{version}/wharf_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "62d149df619d441b97b620cb07a111626524cba809dc7900aceb9f4a13316ed1"
      url "https://github.com/Janne6565/wharf-tui/releases/download/v#{version}/wharf_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "30da778741dfc114a72d2b5c31bf427cc5176f4b2ecdc8baf00a578fc1e61d23"
      url "https://github.com/Janne6565/wharf-tui/releases/download/v#{version}/wharf_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wharf"
  desc "Keyboard-driven terminal SSH client with a local-first encrypted vault"
  homepage "https://wharf.jannekeipert.de"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wharf"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wharf"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Wharf is local-first — run `wharf` and it will create an encrypted vault on
    first start. Write down the 40-character recovery code it shows you once:
    it is the only way back into the vault if you forget the master password.
  EOS
end
