# This file was generated by GoReleaser. DO NOT EDIT.
cask "wharf" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "da15898d6f72346b0b237a224243d3cecf6f9411f48a3a4a2f452e469618d617"
      url "https://github.com/Janne6565/wharf-tui/releases/download/v#{version}/wharf_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "114da33b31e725d1f731c7fee8f3253a7f8ce6d43b497131526852a81a99c33f"
      url "https://github.com/Janne6565/wharf-tui/releases/download/v#{version}/wharf_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b80d80d5638311aceb4d1d8ff0fdd6055c4200b211a312c7730a3ae97aaad567"
      url "https://github.com/Janne6565/wharf-tui/releases/download/v#{version}/wharf_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5554f1e780d97f781b19ba64b337b82854b33daf07d39ab8b21e64806332a297"
      url "https://github.com/Janne6565/wharf-tui/releases/download/v#{version}/wharf_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wharf"
  desc "Keyboard-driven terminal SSH client with a local-first encrypted vault"
  homepage "https://wharf.jannekeipert.de"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wharf"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wharf"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Wharf is local-first — run `wharf` and it will create an encrypted vault on
    first start. Write down the 40-character recovery code it shows you once:
    it is the only way back into the vault if you forget the master password.
  EOS
end
