# This file was generated by GoReleaser. DO NOT EDIT.
cask "wharf" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "2aaedd200e516f2ad387de3fdfe9d2e433fd0eb296c706f11563535b5c127e14"
      url "https://github.com/Janne6565/wharf-tui/releases/download/v#{version}/wharf_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3e4a6b62eed4178364d171fde62037cb9d2f428ed508834c5edd923ea43bf375"
      url "https://github.com/Janne6565/wharf-tui/releases/download/v#{version}/wharf_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "51ff1ad0dc6a46fa3b4bd57a2ec07fc42d399244adee86696f7ea5c2e15c2576"
      url "https://github.com/Janne6565/wharf-tui/releases/download/v#{version}/wharf_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e288f73de59758e1ce1580bffc2ef48f4f6f94a355a3731bf15435aa07e4038b"
      url "https://github.com/Janne6565/wharf-tui/releases/download/v#{version}/wharf_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wharf"
  desc "Keyboard-driven terminal SSH client with a local-first encrypted vault"
  homepage "https://wharf.jannekeipert.de"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wharf"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wharf"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Wharf is local-first — run `wharf` and it will create an encrypted vault on
    first start. Write down the 40-character recovery code it shows you once:
    it is the only way back into the vault if you forget the master password.
  EOS
end
